README.md
- Added tags to show number of open issues and PRs
- Added a section to show all the contributors to the repo
=> Adding tags and contributors on the readme.MD

GIT/Common GIT Commands.md
some of the commonly used GIT commands
=> add common GIT commands

Good-First-Issues/Hello_World.cpp
This Particular Commit have a program to print Hello World in C++ Language.
=> Resolve Issue #60

Good-First-Issues/pair_with_give_sum.cpp
=> Resolve issue #27

Stack.cpp, TwoStacks.cpp
)Includes a separate file containing the solution for #10)
=> Solution for #11

CP-DSA-resources/README.md, ML/README.md, Other-Tech-resources/README.md, README.md
1) Add ML resources from intro to ML session organised by PEC ACM CSS-ML team
2) Add Other-Tech-resources folder for all the resources related to other tech not mentioned in resource table
3) Add SQL resources
=> Add ML resources from intro to ML session & Add Other-Tech-resources folder

Good-First-Issues/Good_Pairs.py
Added Code for Number of Good Pairs problem.
=> #31 Issue Resolved

Good-First-Issues/Sliding_Window_Max.cpp
=> Sliding window maximum

Good-First-Issues/four_pair_sum.cpp
=> Four elements sum

Good-First-Issues/Row_with_Max_1s.py
Added code for Row_with_Max_1s.py
=> #5 Issue Resolved

.gitignore, Good-First-Issues/min_stack.cpp
Cpp program for #26 
- Fixes #26 
Implemented the required functions and gives correct output
=> Resolved Min stack #26

Good-First-Issues/generic_tree_level_wise_order.cpp
Linked Issue: #33 
added generic_tree_level_wise_order.cpp
Signed-off-by: OjusWiZard <ojuswimail@gmail.com>
=> Level-wise order of a Generic Tree #33

Good-First-Issues/nearest_smaller_number.cpp
- Fixes #24 
Please accept this towards my hacktoberfest contributions
=> Fix issue #24

Good-First-Issues/LongestConsecutiveSubsequence.py
Added Code for Longest Consecutive Subsequence Problem
#121
=> Fixes #121 Issue

Good-First-Issues/QueueUsingLL.cpp
This commit contains code for implementation of Queue using Linked List. #39
Performs the Tasks: 
enqueue (int x) // Insert an element to queue
deque() //removes an element from queue
size() //returns the number of elements present in the queue
=> Resolved Issue #39

Web-Dev-resources/README.md
=> Added Resources for web development

Good-First-Issues/SlidingWindowMax.cpp
Program to find the maximum element for each and every contiguous subarray of size k, within the array provided by the user.
Solved in C++, using deques.
=> Resolved Issue#9

Good-First-Issues/Row_With_Max_1s.cpp
Solved Row With Max1s in Cpp with TC - O(m+n)
=> Resolve Issue #5 - Row with max 1s

Good-First-Issues/Nearest_Smallest_to_left.py
=> #24 Issue Resolved

Good-First-Issues/GenerateBinaryfromQ.py
This commit has a program to generate a binary sequence of 1 to N. 
Solved using Python as issue#41 had already been fixed in some other language.
=> Resolved Issue #41 Using Python

Blockchain/10 Free Blockchain Resources.md
Here are some free Blockchain resources
=> Create 10 Free Blockchain Resources.md

CP-DSA-resources/README.md, Good-First-Issues/max_rectangle.py
=> Added CP-DSA Resources

CP-DSA-resources/README.md
added youtube playlist , unacdemy course which i personally did for getting ahead in cp and the book i followed.
=> Added Cp/Dsa sources

Good-First-Issues/StackUsingQs.cpp
Contains C++ implementation of stack using two queues.
=> Resolved Issue #169

Good-First-Issues/LargestArea.cpp
This commit contains a program to calculate the maximum rectangular area that can be formed in a given histogram.
Language used: C++
=> Resolved Issue #25

Good-First-Issues/Implementing_Hashmap.cpp
Solved issue #142 . Works for non negative integers.
=> Resolve Issue Implementing Hashmap #142

Good-First-Issues/knapsack01.cpp
=> Solved Issue#146 Knapsack01

Web-Dev-resources/README.md
I have added some useful resources to learn Web Devlopment. Kindly merged it.
=> Web_dev_resources.md

Good-First-Issues/KaratsubaMultiplication.py
This commit contains a Python program to execute Karatsuba Multiplication for two binary strings and output the decimal equivalent.
=> Resolved Issue #168

Good-First-Issues/Range_of_datatypes.cpp
Program to find Range of various datatypes in c++
=> Program to find Range of various datatypes in c++

Good-First-Issues/Virtual Pointer and Virtual Functions in CPP.md
Contains explanation for Virtual Pointer and Virtual Functions with examples.
=> Explanation for Virtual pointers and Virtual functions in C++

PEC-Courses/README.md
=> Added README for PEC-COURSES
